### ISSUE TITLE
help for ParmEd

### ISSUE THREAD

**Issue by hainm** [swails/ParmEd#7]
Should you add more exceptions for command line when using ParmEd.py?

Like typing "help?" will cause error (program exit)

help(source) causes error and program exits. 

"TypeError: cannot concatenate 'str' and 'ArgumentList' objects"

I think it's good to be compatible with ipython syntax.

Hai

**Comment by swails** [comment]
Closing this, since it's getting stale.  A quick recap:

You can get iPython (or Python-) style help inside the parmed.py interpreter via the ! shell bang:

```
$ parmed.py -ne
Reading input from STDIN...
> !help(ParmedActions.addljtype)
```

This is clunky, and `?addLJType` or `help addLJType` is better.  Inside the iPython (or Python) interpreters, you can import directly from ParmedTools, and use the built-in help there:

```Python
>>> from ParmedTools import addLJType, change
>>> help(addLJType)
>>> help(change)
```

**Comment by hainm** [comment]
Kool
